/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a ipc_adapt -p ipc_proxy -i dbus-defs.h ipc-server.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef IPC_ADAPT_H_1291340462
#define IPC_ADAPT_H_1291340462

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "dbus-defs.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface local.BerndStramm.permute.IpcServer
 */
class IpcServerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "local.BerndStramm.permute.IpcServer")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"local.BerndStramm.permute.IpcServer\">\n"
"    <method name=\"TakeFile\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    IpcServerAdaptor(QObject *parent);
    virtual ~IpcServerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void TakeFile(const QString &name);
Q_SIGNALS: // SIGNALS
};

#endif
