/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a ipc_adapt -p ipc_proxy -i dbus-defs.h ipc-server.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef IPC_PROXY_H_1291340462
#define IPC_PROXY_H_1291340462

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "dbus-defs.h"

/*
 * Proxy class for interface local.BerndStramm.permute.IpcServer
 */
class LocalBerndStrammPermuteIpcServerInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "local.BerndStramm.permute.IpcServer"; }

public:
    LocalBerndStrammPermuteIpcServerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~LocalBerndStrammPermuteIpcServerInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> TakeFile(const QString &name)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(name);
        return asyncCallWithArgumentList(QLatin1String("TakeFile"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace local {
  namespace BerndStramm {
    namespace permute {
      typedef ::LocalBerndStrammPermuteIpcServerInterface IpcServer;
    }
  }
}
#endif
