/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a ipc_adapt -p ipc_proxy -i dbus-defs.h ipc-server.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "ipc_adapt.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class IpcServerAdaptor
 */

IpcServerAdaptor::IpcServerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

IpcServerAdaptor::~IpcServerAdaptor()
{
    // destructor
}

void IpcServerAdaptor::TakeFile(const QString &name)
{
    // handle method call local.BerndStramm.permute.IpcServer.TakeFile
    QMetaObject::invokeMethod(parent(), "TakeFile", Q_ARG(QString, name));
}

